{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-application-01-to-application-02
  namespace: project-ipv6
spec:
  podSelector:
    matchLabels:
      app: application-02
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: application-02
        - podSelector:
            matchExpressions:
              - key: app
                operator: NotIn
                values:
                  - application-01
{{- end }}