name: docker-github-actions

run-name: ${{ github.actor }} docker pipeline

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  lint:
    name: lint dockerfiles
    runs-on: ubuntu-test
    steps:
     - name: Checkout Code
       uses: actions/checkout@v3
      